/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedCapacityRouteImport } from './routes/_authenticated/capacity'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedDailyLogRouteImport } from './routes/_authenticated/daily-log'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as ApiSyncEmailRouteImport } from './routes/api/sync/email'
import { Route as ApiSyncInstagramRouteImport } from './routes/api/sync/instagram'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCapacityRoute = AuthenticatedCapacityRouteImport.update({
  id: '/capacity',
  path: '/capacity',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDailyLogRoute = AuthenticatedDailyLogRouteImport.update({
  id: '/daily-log',
  path: '/daily-log',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiSyncEmailRoute = ApiSyncEmailRouteImport.update({
  id: '/api/sync/email',
  path: '/api/sync/email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncInstagramRoute = ApiSyncInstagramRouteImport.update({
  id: '/api/sync/instagram',
  path: '/api/sync/instagram',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/capacity': typeof AuthenticatedCapacityRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/daily-log': typeof AuthenticatedDailyLogRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/sync/email': typeof ApiSyncEmailRoute
  '/api/sync/instagram': typeof ApiSyncInstagramRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/capacity': typeof AuthenticatedCapacityRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/daily-log': typeof AuthenticatedDailyLogRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
  '/api/sync/email': typeof ApiSyncEmailRoute
  '/api/sync/instagram': typeof ApiSyncInstagramRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/capacity': typeof AuthenticatedCapacityRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRoute
  '/_authenticated/daily-log': typeof AuthenticatedDailyLogRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/api/sync/email': typeof ApiSyncEmailRoute
  '/api/sync/instagram': typeof ApiSyncInstagramRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/capacity'
    | '/clients'
    | '/daily-log'
    | '/leads'
    | '/settings'
    | '/api/sync/email'
    | '/api/sync/instagram'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/reset-password'
    | '/capacity'
    | '/clients'
    | '/daily-log'
    | '/leads'
    | '/settings'
    | '/'
    | '/api/sync/email'
    | '/api/sync/instagram'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/reset-password'
    | '/_authenticated/capacity'
    | '/_authenticated/clients'
    | '/_authenticated/daily-log'
    | '/_authenticated/leads'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/api/sync/email'
    | '/api/sync/instagram'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiSyncEmailRoute: typeof ApiSyncEmailRoute
  ApiSyncInstagramRoute: typeof ApiSyncInstagramRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/capacity': {
      id: '/_authenticated/capacity'
      path: '/capacity'
      fullPath: '/capacity'
      preLoaderRoute: typeof AuthenticatedCapacityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/daily-log': {
      id: '/_authenticated/daily-log'
      path: '/daily-log'
      fullPath: '/daily-log'
      preLoaderRoute: typeof AuthenticatedDailyLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/sync/email': {
      id: '/api/sync/email'
      path: '/api/sync/email'
      fullPath: '/api/sync/email'
      preLoaderRoute: typeof ApiSyncEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync/instagram': {
      id: '/api/sync/instagram'
      path: '/api/sync/instagram'
      fullPath: '/api/sync/instagram'
      preLoaderRoute: typeof ApiSyncInstagramRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCapacityRoute: typeof AuthenticatedCapacityRoute
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRoute
  AuthenticatedDailyLogRoute: typeof AuthenticatedDailyLogRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCapacityRoute: AuthenticatedCapacityRoute,
  AuthenticatedClientsRoute: AuthenticatedClientsRoute,
  AuthenticatedDailyLogRoute: AuthenticatedDailyLogRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiSyncEmailRoute: ApiSyncEmailRoute,
  ApiSyncInstagramRoute: ApiSyncInstagramRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
